const productList = [
  {
    id: 1,
    productImage:
      "https://cdn.shopify.com/s/files/1/0661/7423/products/life-is-better-when-you-dance-style-back-right_1080x.jpg?v=1639393852",
    productImageText: "Tshirt",
    productName: "Oversized Tshirt",
    productPrice: 500,
    productQuantity: 50,
    productRating: 3,
  },
  {
    id: 2,
    productImage:
      "https://m.media-amazon.com/images/I/51ATCvhe0nL._AC_UX385_.jpg",
    productImageText: "Jacket",
    productName: "Girls Ripped Jeans",
    productPrice: 2200,
    productQuantity: 40,
    productRating: 2,

  },
  {
    id: 3,
    productImage:
      "https://cdn.shopify.com/s/files/1/0661/7423/products/game-day-front_1080x.jpg?v=1655537837",
    productImageText: "Jeans",
    productName: "Bomber Jacket",
    productPrice: 2500,
    productQuantity: 10,
    productRating: 5,

  },
  {
    id: 4,
    productImage:
      "https://cdn.shopify.com/s/files/1/0661/7423/products/bad-influence-front.jpg?v=1644844926",
    productImageText: "Jeans",
    productName: "Bad Influence",
    productPrice: 2400,
    productQuantity: 10,
    productRating: 5,
  },
  {
    id: 5,
    productImage:
      "https://m.media-amazon.com/images/I/61vhT+37vhL._AC_UX385_.jpg",
    productImageText: "Jeans",
    productName: "Boys Ripped Jeans",
    productPrice: 1800,
    productQuantity: 10,
    productRating: 4.2,
  },
  {
    id: 6,
    productImage:
      "https://cdn.shopify.com/s/files/1/0661/7423/products/hoodiedoobiedoo-model-front-view_1080x.jpg?v=1655538360",
    productImageText: "Jeans",
    productName: "hoodiedoobiedoo",
    productPrice: 2700,
    productQuantity: 10,
    productRating: 5,
  },
  {
    id: 7,
    productImage:"https://valken-weblinc.netdna-ssl.com/product_images/t-shirt-valken-wit/5fd126c044ee183d507404d7/zoom.jpg?c=1607542464",
    productImageText: "Jeans",
    productName: "Printed T-shirt",
    productPrice: 1100,
    productQuantity: 10,
    productRating: 4.3,
  },
  {
    id: 8,
    productImage:"https://www.differio.com/media/catalog/product/cache/0a727dd2e0a45cdfc82e01aae0d95d43/i/m/img_1062.jpg",
    productImageText: "Jeans",
    productName: "Ripped Shorts",
    productPrice: 1900,
    productQuantity: 10,
    productRating: 5,
  },
  {
    id: 8,
    productImage:"https://cdn.shopify.com/s/files/1/0661/7423/products/feel-the-fear-style-back.jpg?v=1621405339",
    productImageText: "Jeans",
    productName: "saVVdhan T-shirt",
    productPrice: 1600,
    productQuantity: 10,
    productRating: 5,
  },
  {
    id: 9,
    productImage:"https://www.pngall.com/wp-content/uploads/5/Men-Jeans-PNG-HD-Image.png",
    productImageText: "Denim Jeans",
    productName: "Denim Jeans",
    productPrice: 1900,
    productQuantity: 10,
    productRating: 5,
  },
   {
    id: 10,
    productImage:"https://m.media-amazon.com/images/I/71AgUK2NGPL._UX569_.jpg",
    productImageText: "Denim Jeans",
    productName: "PowerLook Shirt",
    productPrice: 900,
    productQuantity: 10,
    productRating: 5,
  },
   {
    id: 11,
    productImage:"https://m.media-amazon.com/images/I/71LI7y2Z4LL._UL1024_.jpg",
    productImageText: "Denim Jeans",
    productName: "Printed Shirt",
    productPrice: 900,
    productQuantity: 10,
    productRating: 5,
  },
   {
    id: 12,
    productImage:"https://cdn.shopify.com/s/files/1/0661/7423/products/sunset-sherbet-front-zoom_250x250@2x.jpg?v=1658567190",
    productImageText: "Denim Jeans",
    productName: "Sun-Set Share Bet",
    productPrice: 1100,
    productQuantity: 10,
    productRating: 5,
  },
  {
    id: 13,
    productImage:"https://cdn.shopify.com/s/files/1/0661/7423/products/dream-cream-back.jpg?v=1630389483",
    productImageText: "Denim Jeans",
    productName: "Dream Cream T-shirt",
    productPrice: 1300,
    productQuantity: 10,
    productRating: 5,
  },
  {
    id: 14,
    productImage:"https://cdn.shopify.com/s/files/1/0661/7423/products/life-is-better-when-you-paint-style-back_250x250@2x.jpg?v=1639395982",
    productImageText: "Denim Jeans",
    productName: "Day Black T-shirt",
    productPrice: 800,
    productQuantity: 10,
    productRating: 5,
  },
  {
    id: 15,
    productImage:"https://cdn.shopify.com/s/files/1/0661/7423/products/eat-together-style-front.jpg?v=1655538137",
    productImageText: "Denim Jeans",
    productName: "Go-Together T-shirt",
    productPrice: 800,
    productQuantity: 10,
    productRating: 5,
  },
  
  
  
];
export default productList;
